### ISSUE TITLE
Error in time variable specification with YamlModel

### ISSUE THREAD

**Issue by dilpath** [yaml2sbml-dev/yaml2sbml#38]
```python
from tempfile import NamedTemporaryFile
from yaml2sbml import YamlModel
model = YamlModel()
model.set_time('t')
with NamedTemporaryFile(suffix='.xml') as f:
    model.write_to_sbml(f.name, over_write=True)
```
produces
```
Traceback (most recent call last):
    model.write_to_sbml(f.name, over_write=True)
  File "yaml2sbml/YamlModel.py", line 116, in write_to_sbml
    sbml_as_string = _parse_yaml_dict(reduced_model_dict)
  File "yaml2sbml/yaml2sbml.py", line 73, in _parse_yaml_dict
    _convert_yaml_blocks_to_sbml(model, yaml_dict)
  File "yaml2sbml/yaml2sbml.py", line 152, in _convert_yaml_blocks_to_sbml
    function_dict[block](model, yaml_dic[block])
  File "yaml2sbml/yaml2sbml/yaml2sbml.py", line 171, in _read_time_block
    if time_dic['variable'] == 'time':
TypeError: list indices must be integers or slices, not str
```

This can be fixed by changing the [specification of the time variable](https://github.com/yaml2sbml-dev/yaml2sbml/blob/master/yaml2sbml/YamlModel.py#L187) from
```python
        self._yaml_model['time'] = [time_variable]
```
to
```python
        self._yaml_model['time'] = {'variable': time_variable}
```
In the context of the YAML model file, this would be equivalent to changing
```yaml
time:
- t
```
to
```yaml
time:
  variable: t
```

**Comment by jvanhoefer** [comment]
The problem, that I currently see, is that this is not caught by `model.validate_yaml()`,  so I will have a look into this as well :)
